baseurl = "http://ronkeinan.com/de/"
languageCode = "de-de"
title = "Ron Keinan"
copyright = 'Copyright  © 2016 Ron Keinan.'
googleAnalytics = "UA-81356777-1"
contentdir = "content/de"
publishdir = "public/de"

[ params ]
	author = "Ron Keinan"
	description = "Persönliche Website von Ron Keinan, Komponist, Arrangeur und Produzent"
