baseurl = "http://ronkeinan.com/en/"
languageCode = "en-us"
title = "Ron Keinan"
copyright = 'Copyright © 2016 Ron Keinan.'
googleAnalytics = "UA-81356777-1"
contentdir = "content/en"
publishdir = "public/en"

[ params ]
	author = "Ron Keinan"
	description = "Homepage of Ron Keinan, Composer, Arranger and Producer"
